
 export const  results= [
    {
    vote_average: 8.3,
    title: "Spider-Man: No Way Home",
    overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    release_date: "2021-12-15",
    id: 634649,
    adult: false,
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    vote_count: 9671,
    video: false,
    popularity: 11578.615,
    media_type: "movie"
    },
    {
    "original_language": "en",
    "original_title": "The Adam Project",
    "poster_path": "/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    "video": false,
    "id": 696806,
    "release_date": "2022-03-11",
    "vote_count": 570,
    "adult": false,
    "backdrop_path": "/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
    "vote_average": 7.1,
    "overview": "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
    "title": "The Adam Project",
    "popularity": 1090.761,
    "media_type": "movie"
    },
    {
    original_language: "en",
    original_title: "Turning Red",
    poster_path: "/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    id: 508947,
    video: false,
    overview: "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    release_date: "2022-03-10",
    vote_count: 423,
    adult: false,
    backdrop_path: "/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    vote_average: 7.5,
    title: "Turning Red",
    popularity: 3909.877,
    media_type: "movie"
    },
    {
    vote_average: 8,
    title: "The Batman",
    overview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    release_date: "2022-03-01",
    id: 414906,
    adult: false,
    backdrop_path: "/5P8SmMzSNYikXpxil6BYzJ16611.jpg",
    original_language: "en",
    original_title: "The Batman",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    vote_count: 1850,
    video: false,
    popularity: 2799.005,
    media_type: "movie"
    },
    {
    "title": "Dog",
    "id": 626735,
    "overview": "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
    "release_date": "2022-02-17",
    "adult": false,
    "backdrop_path": "/8T7SS4jU7TmtqrUr45JgZASCTUP.jpg",
    "vote_count": 84,
    "original_language": "en",
    "original_title": "Dog",
    "poster_path": "/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg",
    "vote_average": 7.8,
    "video": false,
    "popularity": 273.661,
    "media_type": "movie"
    },
    {
    "backdrop_path": "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    "original_language": "en",
    "original_title": "Scream",
    "poster_path": "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 916,
    "overview": "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    "release_date": "2022-01-12",
    "id": 646385,
    "title": "Scream",
    "adult": false,
    "popularity": 1283.389,
    "media_type": "movie"
    },
    {
    "release_date": "2021-12-22",
    "title": "The King's Man",
    "adult": false,
    "backdrop_path": "/4OTYefcAlaShn6TGVK33UxLW9R7.jpg",
    "id": 476669,
    "original_title": "The King's Man",
    "poster_path": "/aq4Pwv5Xeuvj6HZKtxyd23e6bE9.jpg",
    "vote_count": 1969,
    "video": false,
    "vote_average": 7,
    "original_language": "en",
    "overview": "As a collection of history's worst tyrants and criminal masterminds gather to plot a war to wipe out millions, one man must race against time to stop them.",
    "popularity": 1272.677,
    "media_type": "movie"
    },
    {
    "backdrop_path": "/2hGjmgZrS1nlsEl5PZorn7EsmzH.jpg",
    "original_language": "en",
    "original_title": "Blacklight",
    "poster_path": "/woBl0cQCCDIVcpitBaul2dmqNjY.jpg",
    "video": false,
    "vote_average": 5.5,
    "vote_count": 134,
    "overview": "Travis Block is a shadowy Government agent who specializes in removing operatives whose covers have been exposed. He then has to uncover a deadly conspiracy within his own ranks that reaches the highest echelons of power.",
    "release_date": "2022-02-10",
    "id": 823625,
    "title": "Blacklight",
    "adult": false,
    "popularity": 3290.397,
    "media_type": "movie"
    },
    {
    "vote_average": 7.3,
    "overview": "Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.",
    "release_date": "2021-12-08",
    "title": "West Side Story",
    "adult": false,
    "backdrop_path": "/exnFsbb9c3fDutTsgtJSWcDmZm0.jpg",
    "vote_count": 644,
    "original_language": "en",
    "original_title": "West Side Story",
    "poster_path": "/yfz3IUoYYSY32tkb97HlUBGFsnh.jpg",
    "video": false,
    "id": 511809,
    "popularity": 637.822,
    "media_type": "movie"
    },
    {
    "backdrop_path": "/g0YNGpmlXsgHfhGnJz3c5uyzZ1B.jpg",
    "original_language": "en",
    "original_title": "Nightmare Alley",
    "poster_path": "/vfn1feL0V9HNSXuLLpaxAW8O6LO.jpg",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 1026,
    "overview": "An ambitious carnival man with a talent for manipulating people with a few well-chosen words hooks up with a female psychiatrist who is even more dangerous than he is.",
    "release_date": "2021-12-02",
    "id": 597208,
    "title": "Nightmare Alley",
    "adult": false,
    "popularity": 1154.069,
    "media_type": "movie"
    },
    {
    "adult": false,
    "backdrop_path": "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    "id": 568124,
    "original_language": "en",
    "original_title": "Encanto",
    "poster_path": "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 5324,
    "overview": "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    "release_date": "2021-11-24",
    "title": "Encanto",
    "popularity": 2271.185,
    "media_type": "movie"
    },
    {
    "original_language": "en",
    "original_title": "Against the Ice",
    "poster_path": "/6FSGYvPEhIx3ThOikGqHmKxeyNN.jpg",
    "video": false,
    "vote_average": 6.9,
    "overview": "In 1909, two explorers fight to survive after they're left behind while on a Denmark expedition in ice-covered Greenland.",
    "release_date": "2022-02-10",
    "vote_count": 156,
    "adult": false,
    "backdrop_path": "/bnMKMhGJuvELSjRp8KpkuDsBDw2.jpg",
    "title": "Against the Ice",
    "id": 836009,
    "popularity": 549.509,
    "media_type": "movie"
    },
    {
    "original_language": "en",
    "original_title": "The Matrix Resurrections",
    "poster_path": "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    "video": false,
    "vote_average": 6.8,
    "title": "The Matrix Resurrections",
    "vote_count": 3253,
    "overview": "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    "release_date": "2021-12-16",
    "id": 624860,
    "adult": false,
    "backdrop_path": "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    "popularity": 850.516,
    "media_type": "movie"
    },
    {
    "original_language": "en",
    "original_title": "Uncharted",
    "poster_path": "/sqLowacltbZLoCa4KYye64RvvdQ.jpg",
    "id": 335787,
    "video": false,
    "vote_average": 7.1,
    "overview": "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    "release_date": "2022-02-10",
    "vote_count": 770,
    "adult": false,
    "backdrop_path": "/cTTggc927lEPCMsWUsdugSj6wAY.jpg",
    "title": "Uncharted",
    "popularity": 794.642,
    "media_type": "movie"
    },
    {
    "video": false,
    "vote_average": 6.5,
    "overview": "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
    "release_date": "2022-02-25",
    "title": "No Exit",
    "adult": false,
    "backdrop_path": "/tAztR7AXEesMQAAi5ncFPSZtYlI.jpg",
    "vote_count": 220,
    "original_language": "en",
    "original_title": "No Exit",
    "poster_path": "/5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
    "popularity": 2114.824,
    "media_type": "movie"
    },
    {
    "original_language": "en",
    "original_title": "Fresh",
    "poster_path": "/tlu71AgaL3EQBBCNGsAwZLPbV5D.jpg",
    "video": false,
    "vote_average": 6.8,
    "vote_count": 150,
    "overview": "Frustrated by scrolling dating apps only to end up on lame, tedious dates, Noa takes a chance by giving her number to the awkwardly charming Steve after a produce-section meet-cute at the grocery store.",
    "release_date": "2022-01-20",
    "title": "Fresh",
    "id": 787752,
    "adult": false,
    "backdrop_path": "/oVv5l6L5Wi5j3gd4P2vt0YvVMOg.jpg",
    "popularity": 107.283,
    "media_type": "movie"
    },
    {
    "overview": "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
    "release_date": "2021-11-03",
    "adult": false,
    "backdrop_path": "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
    "vote_count": 4849,
    "title": "Eternals",
    "original_language": "en",
    "original_title": "Eternals",
    "id": 524434,
    "poster_path": "/bcCBq9N1EMo3daNIjWJ8kYvrQm6.jpg",
    "video": false,
    "vote_average": 7.2,
    "popularity": 1168.471,
    "media_type": "movie"
    },
    {
    "backdrop_path": "/pwpw1veVNW2Sls5sGbA9mqMYN49.jpg",
    "original_language": "ko",
    "original_title": "해적: 도깨비 깃발",
    "poster_path": "/zAp8FqC4pLfqcsEfuHwQflCWsA5.jpg",
    "video": false,
    "vote_average": 6.6,
    "vote_count": 55,
    "overview": "A gutsy crew of Joseon pirates and bandits battle stormy waters, puzzling clues and militant rivals in search of royal gold lost at sea.",
    "release_date": "2022-01-26",
    "id": 591120,
    "title": "The Pirates: The Last Royal Treasure",
    "adult": false,
    "popularity": 782.767,
    "media_type": "movie"
    },
    {
    "original_language": "da",
    "original_title": "Skyggen i mit øje",
    "poster_path": "/eqCdwVKvdmNTt8435cJqh2YX1My.jpg",
    "title": "The Shadow In My Eye",
    "vote_average": 7.6,
    "overview": "On March 21st, 1945, the British Royal Air Force set out on a mission to bomb Gestapo's headquarters in Copenhagen. The raid had fatal consequences as some of the bombers accidentally targeted a school and more than 120 people were killed, 86 of whom were children.",
    "release_date": "2021-10-28",
    "vote_count": 48,
    "video": false,
    "adult": false,
    "backdrop_path": "/6LtEzA3Umx9mc0lq1g8xOfluGPx.jpg",
    "id": 650031,
    "popularity": 111.044,
    "media_type": "movie"
    },
    {
    "original_language": "en",
    "original_title": "Dune",
    "poster_path": "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    "video": false,
    "vote_average": 7.9,
    "vote_count": 6318,
    "overview": "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    "release_date": "2021-09-15",
    "title": "Dune",
    "id": 438631,
    "adult": false,
    "backdrop_path": "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
    "popularity": 379.661,
    "media_type": "movie"
    },
    ]
    